### ISSUE TITLE
Multi-Line Blade Comments

### ISSUE THREAD

**Issue by apintocr** [apintocr/brackets-laravel-blade#1]
## Objective
Blade Comments *{-- CODE --}* should work across multiple lines.

### Information
This should be achieved with Code Mirror.

**Comment by jaguadoromero** [comment]
Please, close this issue, change version number in "package.json" and upload extension in Brackets Extension Registry website for launch the upgrade inside Brackets

**Comment by apintocr** [comment]
@jaguadoromero  you are right, I've just being very busy.
Will do that in the meantime.

thank you for your support :)
