### ISSUE TITLE
Incorporate Form Facade Syntax Highlights

### ISSUE THREAD

**Issue by ikartik90** [apintocr/brackets-laravel-blade#4]
It would be great if along with blade highlights, if we could also support Form Facade Highlights which are way similar and go hand in hand with most blade applications (at least for me).

The code that primarily requires highlight would be that, that falls between:

    {!! !!}
We could then further enhance this by incorporating further highlights for the specific labels etc.

**Comment by apintocr** [comment]
Easy to do. Will add and update!

**Comment by apintocr** [comment]
Added.
Not tested, Will not be able to test soon, please provide feedback.
